/**
 * Layout raiz da aplicação.
 * Aplica o CSS global e define metadados básicos.
 * Utiliza estrutura Next.js App Router com suporte a SSR e hydration.
 */
import './globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body suppressHydrationWarning>{children}</body>
    </html>
  )
}
